version: '3.8'

services:

  call-service:
    build: calls
    container_name: call-service
    restart: always
    environment:
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=calls
      - POSTGRES_USER=calls
      - POSTGRES_DB=calls
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
    networks:
      - call-service

  postgresdb:
    container_name: postgres
    image: postgres:13.3
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=calls
      - POSTGRES_USER=calls
      - POSTGRES_DB=calls
    logging:
      options:
        max-size: 10m
        max-file: "3"
    restart: always
    #volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables and the data
      #- ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

    networks:
      - call-service

networks:
  call-service:
    driver: bridge
    external: true